issue_tracker/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length


class LoginForm(FlaskForm):
    username = StringField('Username', [
        DataRequired(message="Please enter an username.")
    ])
    password = PasswordField('Password', [
        DataRequired(message="Please enter a password."),
        Length(min=6, message="The password should be at least 6 characters long.")
    ])
    submit = SubmitField('Sign In')

issue_tracker/blueprints/main/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from issue_tracker.blueprints.main.forms import LoginForm
from issue_tracker.models import User


main_bp = Blueprint('main_bp', __name__)


@main_bp.route("/")
@login_required
def index_get():
    return render_template("main/index.html")


@main_bp.route("/login", methods=["GET"])
def login_get():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.index_get'))

    form = LoginForm()

    return render_template("main/login.html", form=form)


@main_bp.route("/login", methods=["POST"])
def login_post():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user and user.validate_password(form.password.data):
            login_user(user)
            next_ = request.args.get('next')

            return redirect(next_ or url_for('main_bp.index_get'))

    return redirect(url_for("main_bp.login_get", form=form))


@main_bp.route("/logout", methods=['GET'])
@login_required
def logout_get():
    logout_user()

    return redirect(url_for('main_bp.login_get'))

issue_tracker/templates/main/index.html
{% extends "shared/_layout.html" %}

{% block content %}
    Something goes here...
{% endblock %}

issue_tracker/templates/main/login.html
{% extends "shared/_base_layout.html" %}

{% block title %}Issue Tracker - Login{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
{% endblock %}

{% block content %}
    <body class="text-center">
        <form action="{{ url_for('main_bp.login_post') }}" method="post" class="form-signin">
            {{ form.csrf_token }}

            <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
            {{ form.username.label(class_="sr-only") }}
            {{ form.username(class_="form-control", placeholder="Username") }}

            {{ form.password.label(class_="sr-only") }}
            {{ form.password(class_="form-control") }}

            {{ form.submit(class_="btn btn-lg btn-primary btn-block") }}
            <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
        </form>
    </body>
{% endblock %}